# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 23:42
from __future__ import unicode_literals

from django.contrib.auth.hashers import make_password
from django.db import migrations


def add_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    user = User.objects.create(
        username="foobar",
        email="foobar@gmail.com"
    )
    user.password = make_password("foobar")
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_users),
    ]
